### ISSUE TITLE
ContentKit - Activities - fix typos, improvements

### ISSUE THREAD

**Issue by ladislas** [leka/ios-monorepo#1006]
```[tasklist]
### Tasks
- [ ] https://github.com/leka/ios-monorepo/issues/1460
- [x] color bingo - typos https://github.com/leka/ios-monorepo/pull/1005
- [x] dance freeze - https://github.com/leka/ios-monorepo/pull/1005
```
