### ISSUE TITLE
CI - Improve ChatGPT review

### ISSUE THREAD

**Issue by ladislas** [leka/ios-monorepo#1007]
```[tasklist]
### Tasks
- [ ] Slack message: give more context --> PR link, file list
- [x] Less text, more interesting info --> if nothing to say, say nothing
- [ ] Use of emojis to help reading ✅ ❌
- [x] maybe ask questions separately: l10n/details first, then exercises payload w/ instructions
- [ ] ask to generate the whole file (or part of the file) with suggestions in a separate message
- [ ] generate diff of the two files/part of the file
```
