### ISSUE TITLE
2024/04/04 - Meeting w/ Adrien

### ISSUE THREAD

**Issue by ladislas** [leka/ios-monorepo#1044]
Feedbacks and notes taken during our meeting with Adrien:

```[tasklist]
### Tasks
- [ ] https://github.com/leka/ios-monorepo/issues/1043
- [ ] https://github.com/leka/ios-monorepo/issues/1096
- [ ] https://github.com/leka/ios-monorepo/issues/1097
- [x] account creation - ne pas fermer le modal en cliquant
- [x] choix du profil - quand un seul profil c'est un peu vide - changer l'UI en fonction du nombre de pros comme pour les choices
- [ ] https://github.com/leka/ios-monorepo/issues/1099
- [x] bug sur la modal qui s'affiche en grand --> empêcher de quitter
- [ ] https://github.com/leka/ios-monorepo/issues/1634
- [x] category curriculums - ça dépasse en français
- [x] text = sous titre plus court, plus simple
- [x] parcours = ensemble d'activités
- [x] description --> more...
- [x] sections : garder que le title
- [x] sections : mettre un numéro
- [x] sections curriculums : sous categories
- [x] liste - ajouter les compétences/thème dans une étiquette -- à réfléchir et définir
- [x] code couleur possible
- [x] curriculum details - titre ok, sous-titre ok - short description merged with description
- [x] faire une différentiation entre curriculum details et activity details
```
