### ISSUE TITLE
2024/04/09 - Feedback Aurore

### ISSUE THREAD

**Issue by ladislas** [leka/ios-monorepo#1058]
```[tasklist]
### Tasks
- [ ] https://github.com/leka/ios-monorepo/issues/1055
- [ ] https://github.com/leka/ios-monorepo/issues/1061
- [ ] https://github.com/leka/ios-monorepo/issues/1062
- [ ] https://github.com/leka/ios-monorepo/issues/1117
- [ ] https://github.com/leka/ios-monorepo/issues/1070
- [ ] https://github.com/leka/ios-monorepo/issues/1065
- [ ] https://github.com/leka/ios-monorepo/issues/1118
```
