### ISSUE TITLE
2024/04/11 - Feedback Yann

### ISSUE THREAD

**Issue by HPezz** [leka/ios-monorepo#1068]
```[tasklist]
### Tasks
- [ ] https://github.com/leka/ios-monorepo/issues/1072
- [ ] https://github.com/leka/ios-monorepo/issues/1073
- [ ] https://github.com/leka/ios-monorepo/issues/1074
- [ ] https://github.com/leka/ios-monorepo/issues/1079
- [ ] https://github.com/leka/ios-monorepo/issues/1083
- [ ] https://github.com/leka/ios-monorepo/issues/1082
- [ ] https://github.com/leka/ios-monorepo/issues/1086
- [x] Verification Email - Make the verification mail cleaner
- [ ] https://github.com/leka/ios-monorepo/issues/1094
- [ ] https://github.com/leka/ios-monorepo/issues/1090
- [ ] ~Description - Homogenise conjugation tenses (Touches ou Toucher)~
- [ ] https://github.com/leka/ios-monorepo/issues/1091
- [ ] https://github.com/leka/ios-monorepo/issues/1092
- [ ] https://github.com/leka/ios-monorepo/issues/1095
- [ ] https://github.com/leka/ios-monorepo/issues/1093
```
