### ISSUE TITLE
Game Engine Kit - Ideas, docs & specs

### ISSUE THREAD

**Issue by ladislas** [leka/ios-monorepo#122]
## About

This epic's goal is to gather information, documentation, ideas, brainstormings, specs, stories, and so on, regarding `GameEngineKit`

:warning: **It is important to note** that:

- `GameEngineKit` must not be confused with `ContentKit` - `GameEngineKit` is completely independent of `ContentKit`
- `GameEngineKit` has no understanding of what a `curriculum`, an `activity` or a `step` are, so there should be no mention of them here
- `GameEngineKit` is being designed to represent the essence of the ui/ux of an interaction between a user and Leka

Mainly, `GameEngineKit` works with 3 things:

- `data` - anything feeding the game text, images, colors, videos
- `ui/ux` - how the user interacts with the game (iPad, robot, magic cards)
- `gameplay` - the inner workings of the game, its rules, what is needed to "do" for the user to succeed

When working with Leka, anything the user has to "do" is a function of the above

> Yeah, but what about steps and activities?!

We voluntarily want to ignore them for this phase of development. Once we figure out GameEngineKit, we'll tackle activities and steps, maybe in an `ActivityKit`.

## Definitions, resources

**Game engine:** tools, bricks, libraries provided to the developers to create a game

**Gameplay:** how a user interacts with the game, its rules, etc.

For a deeper understanding of the concepts, please refer to:

- 🌐 [Wikipedia - Game Engine](https://en.wikipedia.org/wiki/Game_engine)
- 🌐 [Wikipedia - Gameplay](https://en.wikipedia.org/wiki/Gameplay)

## Important ideas

As we were working on our educational content, it became quickly clear that it was divided in different things:

- a general topic, i.e. "emotion recognition"
- a specific order, i.e. "touch the person who is happy"
- an interface, i.e. "pictures of people with different emotions"

The order and interface are closely related but are not exclusive.

It is possible to change the order and keep the interface, such as "touch all the persons who are happy".

The interface doesn't change, but something has to, because the user experience is not the same. This is where `gameplay` comes into play (no pun intended).

From the previous example, we also see that the order "touch the person/all the persons" could be extended to "touch the green vegetable" and "touch all the blue dots".

The important part is `touch`, the rest is only `data` tied to the educational goal, which is (mostly) not relevant for development.

## Requirements

To make development faster, cleaner and more reliable, we feel that `GameEngineKit` should be based on the composable architecture.

There must never be any strong dependencies between:

- data/media
- interface
- gameplay

We must be able to switch those as we want, and things should still work. The fact that a specific combination of data, interface and gameplay does or does not make sense from an educational stand point is irrelevant to the discussion.

## First steps

To better grasp and explore how GameEngineKit should be structured, we have decided to start with a simple example:

### Interfaces

We start with two different interfaces:

1. 3 inline
2. 6 in two rows of 3

### Gameplays

Regarding gameplays, we have 3:

1. select the right item --> `1 in 1 / X`
1. select all the right items --> `X in X / Y`
1. select some of the right items --> `X in Y / Z`

### Data

Regarding data to display we have 3:

1. colors
1. images
1. text

## Conclusion

This makes for 18 combinations in total. We'll start small and increment quickly.

## Todo

- [x] https://github.com/leka/ios-monorepo/issues/124
- [x] https://github.com/leka/ios-monorepo/issues/130
- [x] ~add ability to reset game to play again, with a button in the toolbar~
