### ISSUE TITLE
LekaUpdater - Create updating pages step 1 & 2

### ISSUE THREAD

**Issue by YannLocatelli** [leka/ios-monorepo#131]
## Requirements

- n/a

## Related User Stories (from #79)

- En tant que utilisateur référent Leka, je veux connaître le statut (en cours (nombre d'étapes), terminé, erreur) du processus de mise à jour pour ne pas m'inquiéter et savoir quelle attitude adopter
- En tant que utilisateur référent Leka, je veux savoir que je suis sur l'application de mise à jour pour ne pas la confondre avec les autres applications de Leka

## Tasks (Specify validated ✅)

- [x] Etape 1 - Ajouter en titre et sous-titre centrés "Leka Updater", "L'application pour mettre à jour vos robots Leka !"
- [x] Etape 1 - Ajouter le logo LekaUpdater au centre, en grand
- [x] Etape 1 - Ajouter le texte descriptif "La mise à jour est en cours... \n Ne débranchez pas votre robot, laissez le bien sur son socle"
- [x] Etape 1 - Ajouter le numéro de l'étape et le nombre d'étape total sous le texte descriptif
- [x] Etape 1 - Ajouter une barre de chargement dans un cadre à fond blanc, la barre de chargement est verte
- [x] Etape 2 - Ajouter en titre et sous-titre centrés "Leka Updater", "L'application pour mettre à jour vos robots Leka !"
- [x] Etape 2 - Ajouter le logo LekaUpdater au centre, en grand
- [x] Etape 2 - Ajouter le texte descriptif "Votre robot va maintenant redémarrer

## Tasks (Need Specify validation ⌛︎)

- n/a
