### ISSUE TITLE
LekaUpdater - Create updating page step 3 (Final page)

### ISSUE THREAD

**Issue by YannLocatelli** [leka/ios-monorepo#132]
## Requirements

- n/a

## Related User Stories (from #79)

- En tant que utilisateur référent Leka, je veux être informé que la mise à jour est terminée pour être certain que ça s'est bien déroulé
- En tant que utilisateur référent Leka, je veux connaître le statut (en cours (nombre d'étapes), terminé, erreur) du processus de mise à jour pour ne pas m'inquiéter et savoir quelle attitude adopter
- En tant que utilisateur référent Leka, je veux savoir que je suis sur l'application de mise à jour pour ne pas la confondre avec les autres applications de Leka

## Tasks (Specify validated ✅)

- [x] Ajouter en titre et sous-titre centrés "Leka Updater", "L'application pour mettre à jour vos robots Leka !"
- [x] Ajouter l'image du robot sur son socle encerclé en vert avec le checkmark en bas
- [x] Ajouter le texte descriptif "{Nom du robot} \n Votre robot est bien à jour \n 🎉🥳 \n Bravo! \n Le processus est terminé
- [x] Ajouter le bouton pour retourner à la page de connexion, en dessous du texte descriptif, centré
- [x] Ajouter le bouton pour retourner à la page d'informations robot, en haut à gauche
- [x] Ajouter le logo LekaUpdater en pied de page, centré

## Tasks (Need Specify validation ⌛︎)

- n/a
