### ISSUE TITLE
GEK - Make UI and gameplay independent

### ISSUE THREAD

**Issue by ladislas** [leka/ios-monorepo#1390]
```[tasklist]
### Tasks
- [x] specify the gameplays according to the choice types with `process`
- [x] standardize the process
- [ ] https://github.com/leka/ios-monorepo/issues/915
- [x] separate the choice models of the views from those of the gameplays (even if they are similar sometimes)
- [ ] make the views of the gameplays independent
- [ ] GameplayProtocol - add reset
- [x] Gameplay protocol - add iCompelted #1474
- [ ] https://github.com/leka/ios-monorepo/issues/1475
```
