### ISSUE TITLE
LekaUpdater - Connection page

### ISSUE THREAD

**Issue by YannLocatelli** [leka/ios-monorepo#141]
## Requis

- n/a

## Ressources

- #79 
- #89
- #82
- [prototype design](https://xd.adobe.com/view/d3d875e7-402b-4d1b-9ad6-a2c1a2d58d98-868b/)

## Tasks (Specify validated ✅)

- n/a

## Tasks (Need Specify validation ⌛︎)

- [ ] Link ConnectionView with InformationView and UpdatingView
- [ ] Add app information layout (title, logo at bottom)
- [ ] Display available robots
