### ISSUE TITLE
Analytics - General Todo

### ISSUE THREAD

**Issue by ladislas** [leka/ios-monorepo#1596]
```[tasklist]
### Tasks
- [ ] https://github.com/leka/ios-monorepo/issues/1600
- [ ] https://github.com/leka/ios-monorepo/issues/1601
- [ ] https://github.com/leka/ios-monorepo/issues/1602
- [ ] https://github.com/leka/ios-monorepo/issues/1603
- [ ] https://github.com/leka/ios-monorepo/issues/1604
- [ ] https://github.com/leka/ios-monorepo/issues/1597
- [ ] https://github.com/leka/ios-monorepo/issues/1625
- [ ] select_content - add content skills
- [ ] activity_start - add content skills
- [ ] https://github.com/leka/ios-monorepo/issues/1633
- [ ] https://github.com/leka/ios-monorepo/issues/1621
- [ ] Carereceivers - Add diff in carereceiver_edit Event
- [ ] log Caregiver/Carereceiver Delete ?
```
