### ISSUE TITLE
[ble] investigate use of Combine + CoreBluetooth

### ISSUE THREAD

**Issue by ladislas** [leka/ios-monorepo#37]
```[tasklist]
### Tasks
- [x] add CombineCoreBluetooth and try to replicate their example
- [x] learn more about Combine, publishers/subscribers
- [x] define our architecture
- [x] implement example app
- [x] move code to its own module named `BLEKit`
- [x] try using @macteuts's code to connect to the robots
```
