### ISSUE TITLE
ContentKit + GameEngineKit - Last steps before release

### ISSUE THREAD

**Issue by ladislas** [leka/ios-monorepo#373]
General list of things to do before the release

```[tasklist]
### Tasks
- [ ] https://github.com/leka/ios-monorepo/issues/374
- [ ] https://github.com/leka/ios-monorepo/issues/376
- [ ] https://github.com/leka/ios-monorepo/issues/378
- [ ] https://github.com/leka/ios-monorepo/issues/386
- [ ] https://github.com/leka/ios-monorepo/issues/383
- [ ] https://github.com/leka/ios-monorepo/issues/390
- [ ] https://github.com/leka/ios-monorepo/issues/381
- [ ] https://github.com/leka/ios-monorepo/issues/380
- [ ] https://github.com/leka/ios-monorepo/issues/398
- [ ] https://github.com/leka/ios-monorepo/issues/402
- [ ] https://github.com/leka/ios-monorepo/issues/406
- [ ] https://github.com/leka/ios-monorepo/issues/416
- [ ] https://github.com/leka/ios-monorepo/issues/417
- [ ] https://github.com/leka/ios-monorepo/issues/418
- [x] https://github.com/leka/ios-monorepo/issues/422
- [ ] https://github.com/leka/ios-monorepo/issues/436
- [ ] https://github.com/leka/ios-monorepo/issues/430
- [ ] https://github.com/leka/ios-monorepo/issues/451
- [ ] https://github.com/leka/ios-monorepo/issues/462
- [ ] https://github.com/leka/ios-monorepo/issues/463
- [ ] https://github.com/leka/ios-monorepo/issues/467
- [ ] https://github.com/leka/ios-monorepo/issues/498
- [ ] https://github.com/leka/ios-monorepo/issues/505
- [ ] https://github.com/leka/ios-monorepo/issues/534
- [ ] https://github.com/leka/ios-monorepo/issues/541
- [ ] https://github.com/leka/ios-monorepo/issues/544
- [ ] https://github.com/leka/ios-monorepo/issues/539
- [ ] https://github.com/leka/ios-monorepo/issues/550
- [ ] https://github.com/leka/ios-monorepo/issues/558
- [ ] https://github.com/leka/ios-monorepo/issues/557
- [ ] https://github.com/leka/ios-monorepo/issues/563
- [x] add association gameplay
- [x] ContentKit + UIExplorer --> rewrite list of activities as separated yaml files and list them
- [x] add yaml files for all specific activities --> they are actually activities with only one exercices and should be encoded as such
- [x] ContentKit --> handle list of activities @ladislas
```
