### ISSUE TITLE
activity checks

### ISSUE THREAD

**Issue by ladislas** [leka/ios-monorepo#683]
```[tasklist]
### Tasks
- [x] https://github.com/leka/ios-monorepo/issues/686
- [ ] https://github.com/leka/ios-monorepo/pull/693
- [ ] https://github.com/leka/ios-monorepo/pull/692
- [ ] https://github.com/leka/ios-monorepo/pull/728
- [ ] https://github.com/leka/ios-monorepo/pull/742
- [x] add creation date when file added
- [x] add last edited date on creation then on edition
- [ ] https://github.com/leka/ios-monorepo/pull/744
- [ ] https://github.com/leka/ios-monorepo/pull/747
```
