### ISSUE TITLE
curriculum checks

### ISSUE THREAD

**Issue by ladislas** [leka/ios-monorepo#684]
```[tasklist]
### Tasks
- [x] check uuid vs filename
- [x] check name vs filename
- [x] check uuid is unique
- [ ] https://github.com/leka/ios-monorepo/issues/913
- [x] check schema
- [x] check skills exist
- [x] add creation date when file added
- [x] add last edited date on creation then on edition
```
