### ISSUE TITLE
[Epic] - LekaUpdater improvements

### ISSUE THREAD

**Issue by YannLocatelli** [leka/ios-monorepo#79]
## Requirements

- [ ] #82

## User Stories (validés ✅ avec @AuroreLeka | conforme ✅ pour @ladislas)
*En tant que utilisateur référent Leka, je souhaite*

- [x] LekaUpdater - Redesign app in minimum 3 pages: connection, information, update in progress
	- Avoir une page par étape, une action par page max: 
		- connexion au robot, 
		- information robot [mise à jour disponible ou non], 
		- mise à jour en cours [envoie du fichier, redémarrage en cours, mise à jour terminée]
- [x] #749
	- Ne pas à avoir à déconnecter le robot de LekaUpdater pour le connecter à LekaApp et vice versa
- Page de connexion (first page)
	- [x] #89
		- Avoir la même page de connexion au robot que LekaApp afin de d’utiliser un protocole familier
		- Savoir qu’on est dans LekaUpdater → Icône LekaUpdater en haut
	- [x] LekaUpdater - See robot major information
		- Accéder rapidement à l'état du robot pour le SAV (batteries, version OS)
	- [x] #750
		- Savoir quels robots peuvent être mis à jour (Version inférieure) → Utilisation d'une pastille rouge
	- [x] LekaUpdater - Navigate from connection page to information page
		- Savoir si mon robot est connecté, s'il n'est pas connecté de pouvoir le connecter *afin de* passer à l'étape suivante, s'il est connecté (visuel) de pouvoir passer à l'étape suivante
- Page d’informations
	- [x] #92
		- Avoir les informations du robot pour l’identifier [Nom] et pour le SAV [N° de série, Batteries, Version]
		- Cas 1 - S’il y a une mise à jour à faire, avoir une description de ce qu’elle ajoute
		- Cas 1 - S’il y a une mise à jour à faire, avoir un descriptif visuel des pré-requis similaire à ceux du robot (image de batteries doit être à au moins 30%, image d'un robot qui doit être mis en charge)
		- Cas 1 - S’il y a une mise à jour à faire, avoir une confirmation visuelle des conditions remplies
		- Cas 1 - S’il y a une mise à jour à faire, voir apparaître le bouton de mise à jour uniquement lorsque les conditions requises sont validées
		- Cas 1 - S’il y a une mise à jour à faire, savoir approximativement combien de temps me prendra la mise à jour → Préciser où l'ajouter (descriptif de màj, requis pour faire la mise à jour, annoté en dessous du texte du bouton de mise à jour)
		- Cas 2 - Si le robot est à jour, savoir qu’il est à déjà à jour
		- Cas 2 - Si le robot est à jour, avoir une description de ce qui a été ajouté avec la dernière mise à jour
	- [x] LekaUpdater - Navigate back from information page to connection page
		- Pouvoir retourner à la page de connexion *afin de* pouvoir mettre un autre robot à jour

Basé sur [v3-SAV-MAJ Robot- proposition](https://www.dropbox.com/scl/fi/whn654hff70kqh5j58pr6/v3-SAV-MAJ-Robot--proposition.gslides?dl=0&rlkey=5huww36yvjyd09dqc7bapwirx#slide=id.g20f82619eb9_0_0) et [ios-leka_updater issues (github)](https://github.com/leka/ios-leka_updater/issues)

### Notes

Chaque point doit être lu avec en début la phrase indiquée en haut "En tant que...", ceci étant la base de la formulation d'une User Story. 

La présence d'une flèche "→" indique une suggestion de réalisation ou un point d'attention à préciser

---

## User Stories (validés ✅ avec @AuroreLeka | conforme ✅ pour @ladislas) (2e passage)

- En tant que utilisateur référent Leka, je veux que la mise à jour continue quand je ne suis pas sur l'application pour faire autre chose
  - En tant que utilisateur référent Leka, je veux être informé que la mise à jour est terminée pour être certain que ça s'est bien déroulé
- En tant que utilisateur référent Leka, je veux connaître le statut (en cours (nombre d'étapes), terminé, erreur) du processus de mise à jour pour ne pas m'inquiéter et savoir quelle attitude adopter
- En tant que utilisateur référent Leka, je veux savoir que je suis sur l'application de mise à jour pour ne pas la confondre avec les autres applications de Leka
- En tant que responsable clientèle Leka, je veux pouvoir informer les utilisateurs référents Leka qu'une nouvelle mise à jour de l'application (de mise à jour) est disponible pour qu'ils puissent mettre à jour leur robot et pouvoir bénéficier des corrections de bugs et des nouvelles fonctionnalités
- En tant que utilisateur référent Leka, je veux être informé lorsqu'une nouvelle mise à jour du robot est disponible pour mettre à jour mon robot et pouvoir bénéficier des corrections de bugs et des nouvelles fonctionnalités
- En tant que utilisateur référent Leka, je veux mettre plusieurs robots à jour en une fois pour gagner du temps
