### ISSUE TITLE
Dev - Add  DEVELOPER_MODE to help debug the app

### ISSUE THREAD

**Issue by ladislas** [leka/ios-monorepo#865]
```[tasklist]
### Tasks
- [x] create env variable for local debug + testflight
- [ ] https://github.com/leka/ios-monorepo/issues/819
- [x] show/hide side bar section
```
