### ISSUE TITLE
UI - Improvements

### ISSUE THREAD

**Issue by ladislas** [leka/ios-monorepo#882]
<img width="903" alt="Screenshot 2024-03-18 at 18 06 37" src="https://github.com/leka/ios-monorepo/assets/2206544/385c6fa2-ed01-4ab8-a073-961eaf89e64f">

```[tasklist]
### Tasks
- [x] Add profile is not the main action, it should be in the bottom toolbar
- [x] As with care receivers, it might be nice to select first then validate
```

<img width="862" alt="image" src="https://github.com/leka/ios-monorepo/assets/2206544/d6a66ced-370b-42cc-a699-1fdf34d344d5">

```[tasklist]
### Tasks
- [x] use text for "close x"
- [x] for avatar, use `photo.badge.plus`
```

<img width="889" alt="image" src="https://github.com/leka/ios-monorepo/assets/2206544/f6ec79b3-ca60-4048-975a-b850d5fe71d9">

```[tasklist]
### Tasks
- [x] rename title "Liste des professions"
- [x] use text for toolbar buttons
```
