### ISSUE TITLE
Modules - Add UtilsKit

### ISSUE THREAD

**Issue by ladislas** [leka/ios-monorepo#897]
store utility functions/extensions to be shared by all targets

```[tasklist]
### Tasks
- [x] `public extension String { static func random(length: Int)`
- [x] `extension String { func containsEmoji()`
- [x] `public extension String {     var fileURL:`
- [x] `extension String {     var isRasterImageFile:`
```
