### ISSUE TITLE
BLEManager - refactor

### ISSUE THREAD

**Issue by ladislas** [leka/ios-monorepo#96]
```[tasklist]
### Tasks
- [x] remove all cancellables on disconnect
- [x] review use of cancellables outiside class
- [x] review published variables --> are they all needed?
- [x] review use of ObservableObject
- [x] review use of @Published vs Publishers
```
